### ISSUE TITLE
Redshift Driver Support

### ISSUE THREAD

**Issue by jflatter** [geckoboard/sql-dataset#12]
Stitch Data + Redshift + Geckoboard + Chromebit must be a common use case.

Please include Redshift driver support ASAP!!

I love your product.  One baby step left until I have a complete dashboard story without several pieces of software between my data warehouse and a TV.

Thanks

**Comment by jnormington** [comment]
Hey @jflatter,

Just to confirm you are referring to Amazon Redshift right ?

If you we actually test this internally as [Redshift is based on PostgreSQL 8.0.2](http://docs.aws.amazon.com/redshift/latest/dg/c_redshift-and-postgres-sql.html) and it worked just fine with the postgres driver.

However if you have tried this and had some problems we will be happy to help diagnose the issue further

This isn't clear as per the readme, therefore I will look at adding as a supported service

**Comment by jflatter** [comment]
There are separate jdbc driver for Postgres and AWS Redshift.  The syntax has a lot of overlap (>95%) but there are a few gotchas whenever I have tried using one for the other.  Happy to give it a go and relay and specific problems.

**Comment by jnormington** [comment]
Hey @jflatter I just wanted to check-in to see if you had got it working with redshift or ran into some issues ?
