### ISSUE TITLE
Problems with mssql server

### ISSUE THREAD

**Issue by jptechadv** [geckoboard/sql-dataset#18]
Hi,  I am having troubles making this work with MS SQL Server.  I have managed to configure and get it working with MYSQL but when I change the driver to mssql it doesn't work.

I found in another issue the debug versions of the exe so I used that for additional information and I have posted these below.  The version I am using the windows 64bit executable.

When I run the exe with my config I get one of two errors below and they seem to alternate in sequence.

How can I resolve this problem as I don't want to build an app to do exactly what you are doing?

CONFIG FILE:
geckoboard_api_key: {myapikey}
database:
 driver: mssql
 host: server
 username: user
 password: password
 name: db
datasets:
 - name: my.summary
   update_type: replace
   sql: Select StoreID, Storename, LastUpdated from Dashboard
   fields:
    - type: number
      name: StoreID
    - type: string
      name: StoreName
    - type: datetime
      name: LastUpdated

ERROR1:
DEBUG: Loading config geckoboard.datasets.simple.yml
DEBUG: Config finished loading
DEBUG: Validating config
DEBUG: Config validated

DEBUG: Get connection string builder for driver mssql
DEBUG: Got connection string builder using drivers.mssql{}
DEBUG: Building connections string
DEBUG: Built connection string - odbc:server={server};port=1433;user id={user};password={password};database=db;ApplicationIntent=ReadOnly
DEBUG: Building new client
DEBUG: Making new db connection (but not connecting) - %s
DEBUG: Preparing to start processing datasets
No refresh timer specified will process once and exit
DEBUG: Processing dataset my.summary
DEBUG: Querying the database with sql - Select StoreID, Storename, LastUpdated from Dashboard
DEBUG: Finished querying the database
Dataset 'my.summary' errored: Database query failed: Login error: EOF
DEBUG: Finished processing datasets

ERROR2:
DEBUG: Loading config geckoboard.datasets.simple.yml
DEBUG: Config finished loading
DEBUG: Validating config
DEBUG: Config validated

DEBUG: Get connection string builder for driver mssql
DEBUG: Got connection string builder using drivers.mssql{}
DEBUG: Building connections string
DEBUG: Built connection string - odbc:server={server};port=1433;user id={user};password={password};database=db;ApplicationIntent=ReadOnly
DEBUG: Building new client
DEBUG: Making new db connection (but not connecting) - %s
DEBUG: Preparing to start processing datasets
No refresh timer specified will process once and exit
DEBUG: Processing dataset my.summary
DEBUG: Querying the database with sql - Select StoreID, Storename, LastUpdated from Dashboard
DEBUG: Finished querying the database
Dataset 'my.summary' errored: Database query failed: Login error: EOF
DEBUG: Finished processing datasets

**Comment by jptechadv** [comment]
Hi Jon,

I just realised I could try it using a remote session because I set it all up on server as well as dev machine to test.

I added the additional encrypyt: disable param as per your post as follows

geckoboard_api_key: api_key
database:
 driver: mssql
 host: ipaddress
 username: user
 password: pass
 name: db
params:
 encrypt: disable
datasets:
 - name: glamaco.summary
   update_type: replace
   sql: Select StoreID, Storename, LastUpdated from [dbo].Dashboard
   fields:
    - type: number
      name: StoreID
    - type: string
      name: Store Name
    - type: datetime
      name: Last Updated

Next suggestion please? :(


Cheers,

Jason.

**Comment by jptechadv** [comment]
Hi Jon,

I am not sure the connection string builder knows how to deal with the 'encrypt: disable' option as the connection string displayed by the debug version does not show it included in the completed connection string?

Have you been able to add the parameter and see it included in the connection string?

Cheers,
Jason.

**Comment by jnormington** [comment]
Hi @jptechadv 

Sorry was a little busy yesterday - I'm in the London timezone. Hmm thats interesting it should be adding it. Can you try instead moving using the option under tls_config instead like my example below and let me know the outcome.

```yml
geckoboard_api_key: {myapikey}
database:
 driver: mssql
 host: server
 username: user
 password: password
 name: db
 tls_config:
   ssl_mode: disable
datasets:
 - name: my.summary
   update_type: replace
   sql: Select StoreID, Storename, LastUpdated from Dashboard
   fields:
    - type: number
      name: StoreID
    - type: string
      name: StoreName
    - type: datetime
      name: LastUpdated
```

**Comment by jptechadv** [comment]
Hi Jon,

That was it. Everything is working now :)

Need to add this little gotcha to the docs somewhere for the next poor soul who strikes this.

Thanks for your help.

Cheers,
Jason.

**Comment by jnormington** [comment]
Hi Jason,

Great - glad that worked - Yes I'll add a little section of gotcha 👍

**Comment by jnormington** [comment]
Added MSSQL ssl modes which was missing completely and a very brief note along side the options for connection issues.

https://github.com/geckoboard/sql-dataset/commit/51ef080a15804bcce8afbd950cbd02616892a555
