### ISSUE TITLE
Download issues

### ISSUE THREAD

**Issue by mikev10** [geckoboard/sql-dataset#25]
Hi,
I have downloaded the Windows app and try to run the .exe file but nothing happens.

Am I missing something here?

**Comment by jnormington** [comment]
Hi @mikev10,

It sounds like you are doubling clicking the .exe - unfortunately there is no graphical user interface. Its purely command line. So it is executing failing (as there is no config likely) and closing.

Can you try to follow the following steps in the below readme please. **Please start from step 2** **and don't follow step one** - as it links to really old and buggy version. 

https://github.com/geckoboard/sql-dataset/blob/5484aec445988b44b7196b8d0c3ddcaf2fea1eb8/docs/windows_setup.md

Hope that helps

**Comment by mikev10** [comment]
Thank you.

I realized my mistake today. In step 3 of the readme file, I was doing exactly what it was saying which is to run `./sql-dataset -config config.yml`.

However, I needed to put the entire `.exe` filename instead of just `sql-dataset`.
